INSERT INTO breeds (pet_type_id, name) VALUES
(1, 'Affenpinscher'),
(1, 'Afghan Hound'),
(1, 'Airedale Terrier'),
(1, 'Akita'),
(1, 'Alaskan Malamute'),
(1, 'American Bulldog'),
(1, 'American English Coonhound'),
(1, 'American Eskimo Dog'),
(1, 'American Foxhound'),
(1, 'American Hairless Terrier'),
(1, 'American Leopard Hound'),
(1, 'American Staffordshire Terrier'),
(1, 'American Water Spaniel'),
(1, 'Anatolian Shepherd Dog'),
(1, 'Appenzeller Sennenhund'),
(1, 'Australian Cattle Dog'),
(1, 'Australian Kelpie'),
(1, 'Australian Shepherd'),
(1, 'Australian Stumpy Tail Cattle Dog'),
(1, 'Australian Terrier'),
(1, 'Azawakh'),
(1, 'Barbet'),
(1, 'Basenji'),
(1, 'Basset Fauve de Bretagne'),
(1, 'Basset Hound'),
(1, 'Bavarian Mountain Scent Hound'),
(1, 'Beagle'),
(1, 'Bearded Collie'),
(1, 'Beauceron'),
(1, 'Bedlington Terrier'),
(1, 'Belgian Laekenois'),
(1, 'Belgian Malinois'),
(1, 'Belgian Sheepdog'),
(1, 'Belgian Tervuren'),
(1, 'Bergamasco Sheepdog'),
(1, 'Berger Picard'),
(1, 'Bernese Mountain Dog'),
(1, 'Bichon Frise'),
(1, 'Biewer Terrier'),
(1, 'Black and Tan Coonhound'),
(1, 'Black Russian Terrier'),
(1, 'Bloodhound'),
(1, 'Bluetick Coonhound'),
(1, 'Boerboel'),
(1, 'Bohemian Shepherd'),
(1, 'Bolognese'),
(1, 'Border Collie'),
(1, 'Border Terrier'),
(1, 'Borzoi'),
(1, 'Boston Terrier'),
(1, 'Bouvier des Flandres'),
(1, 'Boxer'),
(1, 'Boykin Spaniel'),
(1, 'Bracco Italiano'),
(1, 'Braque du Bourbonnais'),
(1, 'Braque Francais Pyrenean'),
(1, 'Briard'),
(1, 'Brittany'),
(1, 'Broholmer'),
(1, 'Brussels Griffon'),
(1, 'Bull Terrier'),
(1, 'Bulldog'),
(1, 'Bullmastiff'),
(1, 'Cairn Terrier'),
(1, 'Canaan Dog'),
(1, 'Cane Corso'),
(1, 'Cardigan Welsh Corgi'),
(1, 'Carolina Dog'),
(1, 'Catahoula Leopard Dog'),
(1, 'Caucasian Shepherd Dog'),
(1, 'Cavalier King Charles Spaniel'),
(1, 'Central Asian Shepherd Dog'),
(1, 'Cesky Terrier'),
(1, 'Chesapeake Bay Retriever'),
(1, 'Chihuahua'),
(1, 'Chinese Crested'),
(1, 'Chinese Shar-Pei'),
(1, 'Chinook'),
(1, 'Chow Chow'),
(1, 'Cirneco dellâ€™Etna'),
(1, 'Clumber Spaniel'),
(1, 'Cocker Spaniel'),
(1, 'Collie'),
(1, 'Coton de Tulear'),
(1, 'Croatian Sheepdog'),
(1, 'Curly-Coated Retriever'),
(1, 'Czechoslovakian Vlcak'),
(1, 'Dachshund'),
(1, 'Dalmatian'),
(1, 'Dandie Dinmont Terrier'),
(1, 'Danish-Swedish Farmdog'),
(1, 'Deutscher Wachtelhund'),
(1, 'Doberman Pinscher'),
(1, 'Dogo Argentino'),
(1, 'Dogue de Bordeaux'),
(1, 'Drentsche Patrijshond'),
(1, 'Drever'),
(1, 'Dutch Shepherd'),
(1, 'English Cocker Spaniel'),
(1, 'English Foxhound'),
(1, 'English Setter'),
(1, 'English Springer Spaniel'),
(1, 'English Toy Spaniel'),
(1, 'Entlebucher Mountain Dog'),
(1, 'Estrela Mountain Dog'),
(1, 'Eurasier'),
(1, 'Field Spaniel'),
(1, 'Finnish Lapphund'),
(1, 'Finnish Spitz'),
(1, 'Flat-Coated Retriever'),
(1, 'French Bulldog'),
(1, 'French Spaniel'),
(1, 'German Longhaired Pointer'),
(1, 'German Pinscher'),
(1, 'German Shepherd Dog'),
(1, 'German Shorthaired Pointer'),
(1, 'German Spitz'),
(1, 'German Wirehaired Pointer'),
(1, 'Giant Schnauzer'),
(1, 'Glen of Imaal Terrier'),
(1, 'Golden Retriever'),
(1, 'Gordon Setter'),
(1, 'Grand Basset Griffon VendÃ©en'),
(1, 'Great Dane'),
(1, 'Great Pyrenees'),
(1, 'Greater Swiss Mountain Dog'),
(1, 'Greyhound'),
(1, 'Hamiltonstovare'),
(1, 'Hanoverian Scenthound'),
(1, 'Harrier'),
(1, 'Havanese'),
(1, 'Hokkaido'),
(1, 'Hovawart'),
(1, 'Ibizan Hound'),
(1, 'Icelandic Sheepdog'),
(1, 'Irish Red and White Setter'),
(1, 'Irish Setter'),
(1, 'Irish Terrier'),
(1, 'Irish Water Spaniel'),
(1, 'Irish Wolfhound'),
(1, 'Italian Greyhound'),
(1, 'Jagdterrier'),
(1, 'Japanese Chin'),
(1, 'Japanese Spitz'),
(1, 'Jindo'),
(1, 'Kai Ken'),
(1, 'Karelian Bear Dog'),
(1, 'Keeshond'),
(1, 'Kerry Blue Terrier'),
(1, 'Kishu Ken'),
(1, 'Komondor'),
(1, 'Kromfohrlander'),
(1, 'Kuvasz'),
(1, 'Labrador Retriever'),
(1, 'Lagotto Romagnolo'),
(1, 'Lakeland Terrier'),
(1, 'Lancashire Heeler'),
(1, 'Lapponian Herder'),
(1, 'Leonberger'),
(1, 'Lhasa Apso'),
(1, 'LÃ¶wchen'),
(1, 'Maltese'),
(1, 'Manchester Terrier (Standard)'),
(1, 'Manchester Terrier (Toy)'),
(1, 'Mastiff'),
(1, 'Miniature American Shepherd'),
(1, 'Miniature Bull Terrier'),
(1, 'Miniature Pinscher'),
(1, 'Miniature Schnauzer'),
(1, 'Mountain Cur'),
(1, 'Mudi'),
(1, 'Neapolitan Mastiff'),
(1, 'Nederlandse Kooikerhondje'),
(1, 'Newfoundland'),
(1, 'Norfolk Terrier'),
(1, 'Norrbottenspets'),
(1, 'Norwegian Buhund'),
(1, 'Norwegian Elkhound'),
(1, 'Norwegian Lundehund'),
(1, 'Norwich Terrier'),
(1, 'Nova Scotia Duck Tolling Retriever'),
(1, 'Old English Sheepdog'),
(1, 'Otterhound'),
(1, 'Papillon'),
(1, 'Parson Russell Terrier'),
(1, 'Pekingese'),
(1, 'Pembroke Welsh Corgi'),
(1, 'Perro de Presa Canario'),
(1, 'Peruvian Inca Orchid'),
(1, 'Petit Basset Griffon VendÃ©en'),
(1, 'Pharaoh Hound'),
(1, 'Plott Hound'),
(1, 'Pointer'),
(1, 'Polish Lowland Sheepdog'),
(1, 'Pomeranian'),
(1, 'Poodle (Miniature)'),
(1, 'Poodle (Standard)'),
(1, 'Poodle (Toy)'),
(1, 'Porcelaine'),
(1, 'Portuguese Podengo'),
(1, 'Portuguese Podengo Pequeno'),
(1, 'Portuguese Pointer'),
(1, 'Portuguese Sheepdog'),
(1, 'Portuguese Water Dog'),
(1, 'Pudelpointer'),
(1, 'Pug'),
(1, 'Puli'),
(1, 'Pumi'),
(1, 'Pyrenean Mastiff'),
(1, 'Pyrenean Shepherd'),
(1, 'Rafeiro do Alentejo'),
(1, 'Rat Terrier'),
(1, 'Redbone Coonhound'),
(1, 'Rhodesian Ridgeback'),
(1, 'Romanian Mioritic Shepherd Dog'),
(1, 'Rottweiler'),
(1, 'Russell Terrier'),
(1, 'Russian Toy'),
(1, 'Russian Tsvetnaya Bolonka'),
(1, 'Saint Bernard'),
(1, 'Saluki'),
(1, 'Samoyed'),
(1, 'Schapendoes'),
(1, 'Schipperke'),
(1, 'Scottish Deerhound'),
(1, 'Scottish Terrier'),
(1, 'Sealyham Terrier'),
(1, 'Segugio Italiano'),
(1, 'Shetland Sheepdog'),
(1, 'Shiba Inu'),
(1, 'Shih Tzu'),
(1, 'Shikoku'),
(1, 'Siberian Husky'),
(1, 'Silky Terrier'),
(1, 'Skye Terrier'),
(1, 'Sloughi'),
(1, 'Slovakian Wirehaired Pointer'),
(1, 'Slovensky Cuvac'),
(1, 'Slovensky Kopov'),
(1, 'Small Munsterlander Pointer'),
(1, 'Smooth Fox Terrier'),
(1, 'Soft Coated Wheaten Terrier'),
(1, 'Spanish Mastiff'),
(1, 'Spanish Water Dog'),
(1, 'Spinone Italiano'),
(1, 'Stabyhoun'),
(1, 'Staffordshire Bull Terrier'),
(1, 'Standard Schnauzer'),
(1, 'Sussex Spaniel'),
(1, 'Swedish Lapphund'),
(1, 'Swedish Vallhund'),
(1, 'Taiwan Dog'),
(1, 'Teddy Roosevelt Terrier'),
(1, 'Thai Ridgeback'),
(1, 'Tibetan Mastiff'),
(1, 'Tibetan Spaniel'),
(1, 'Tibetan Terrier'),
(1, 'Tornjak'),
(1, 'Tosa'),
(1, 'Toy Fox Terrier'),
(1, 'Transylvanian Hound'),
(1, 'Treeing Tennessee Brindle'),
(1, 'Treeing Walker Coonhound'),
(1, 'Vizsla'),
(1, 'Weimaraner'),
(1, 'Welsh Springer Spaniel'),
(1, 'Welsh Terrier'),
(1, 'West Highland White Terrier'),
(1, 'Wetterhoun'),
(1, 'Whippet'),
(1, 'Wire Fox Terrier'),
(1, 'Wirehaired Pointing Griffon'),
(1, 'Wirehaired Vizsla'),
(1, 'Working Kelpie'),
(1, 'Xoloitzcuintli'),
(1, 'Yakutian Laika'),
(1, 'Yorkshire Terrier'),
(2, 'Domestic Shorthair'),
(2, 'Domestic Medium hair'),
(2, 'Domestic'),
(2, 'Domestic Longhair'),
(2, 'Ragdoll'),
(2, 'Tabby'),
(2, 'Burmese'),
(2, 'Cross Breed'),
(2, 'Russian Blue'),
(2, 'Bengal'),
(2, 'British Shorthair'),
(2, 'Siamese'),
(2, 'Maine Coon'),
(2, 'Tortoiseshell'),
(2, 'Persian'),
(2, 'Birman'),
(2, 'Devon Rex'),
(2, 'Siberian'),
(2, 'Sphynx'),
(2, 'Abyssinian'),
(2, 'Exotic Shorthair'),
(2, 'Oriental'),
(2, 'Scottish Fold'),
(2, 'Australian Mist'),
(2, 'Oriental Shorthair'),
(2, 'Burmilla'),
(2, 'American Shorthair'),
(2, 'Himalayan Persian'),
(2, 'Somali'),
(2, 'Ocicat'),
(2, 'Selkirk rex'),
(2, 'Turkish Van'),
(2, 'Scottish Shorthair'),
(2, 'Munchkin'),
(2, 'Egyptian Mau'),
(2, 'Norwegian Forest'),
(2, 'American Curl'),
(2, 'Aphrodite'),
(2, 'Oriental Bicolour'),
(2, 'Tiffany'),
(2, 'Australian Tiffanie'),
(2, 'German Rex'),
(2, 'Pixiebob'),
(2, 'Peterbald');

